version: "3.8"

services:
  backend:
    container_name: backend
    build: ./api
    ports:
      - 3000:3000
    volumes:
      - ./api/src:/app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 3000
  frontend:
    container_name: ui
    build: ./ui
    volumes:
      - "./ui:/app"
    ports:
      - 8020:8020
